services:
  # zkML News Service Backend
  - type: web
    name: zkml-news-service
    env: node
    region: oregon
    plan: free
    buildCommand: cd news-service && npm install
    startCommand: cd news-service && node src/index.js
    healthCheckPath: /status
    envVars:
      # Blockchain Configuration (Base Mainnet)
      - key: BASE_MAINNET_RPC_URL
        sync: false
      - key: ORACLE_PRIVATE_KEY
        sync: false

      # Contract Addresses (Base Mainnet)
      - key: NEWS_ORACLE_CONTRACT_ADDRESS
        value: 0xe92c7aE9E894a8701583a43363676ff878d5b6ed
      - key: VERIFICATION_REGISTRY_ADDRESS
        value: 0x909fbFbFE9F7Bdb4d1a6e02F2E91d3f367555b07
      - key: VALIDATION_REGISTRY_ADDRESS
        value: 0x04C6276830DA145ee465194131B7beC22aa2d0d3
      - key: TRADING_AGENT_ADDRESS
        value: 0x0D43DC16eFC1322Df3CE2B2852558993918A122B
      - key: NEWS_VERIFIER_ADDRESS
        value: 0x0590f2DFa80BCCc948aDb992737305f2FD01ceba
      - key: GROTH16_VERIFIER
        value: 0xebE04Fa57C6cb7294DD7B3D16c166c3424092168

      # Uniswap V3 (Base Mainnet)
      - key: UNISWAP_V3_ROUTER
        value: 0x2626664c2603336E57B271c5C0b26F421741e481
      - key: WETH_ADDRESS
        value: 0x4200000000000000000000000000000000000006
      - key: USDC_ADDRESS
        value: 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913

      # News Sources
      - key: COINDESK_RSS_URL
        value: https://www.coindesk.com/arc/outboundfeeds/rss/
      - key: CRYPTOCOMPARE_API_KEY
        value: ""

      # Service Configuration
      - key: POLL_INTERVAL_MINUTES
        value: 5
      - key: MIN_CONFIDENCE_THRESHOLD
        value: 60
      - key: MAX_CLASSIFICATIONS_PER_CYCLE
        value: 5
      - key: PORT
        value: 3000

      # JOLT-Atlas Configuration
      - key: JOLT_ATLAS_PATH
        value: ../zkml-model
      - key: PROOF_TIMEOUT_MS
        value: 5000

      # Logging
      - key: LOG_LEVEL
        value: info

      # Trading Configuration
      - key: ENABLE_AUTO_TRADE
        value: "true"

      # zkML Proof Configuration
      - key: USE_REAL_PROOFS
        value: "true"

      # Node Environment
      - key: NODE_ENV
        value: production

  # zkML UI Frontend
  - type: web
    name: zkml-ui
    env: node
    region: oregon
    plan: free
    buildCommand: cd ui && npm install
    startCommand: cd ui && node server.js
    healthCheckPath: /health
    envVars:
      # API Configuration
      - key: NEWS_SERVICE_URL
        value: https://zkml-news-service.onrender.com
      - key: PORT
        value: 3001

      # Blockchain Configuration (Base Mainnet for UI monitoring)
      - key: BASE_MAINNET_RPC_URL
        sync: false

      # Contract Addresses (same as backend)
      - key: NEWS_ORACLE_CONTRACT_ADDRESS
        value: 0xe92c7aE9E894a8701583a43363676ff878d5b6ed
      - key: VERIFICATION_REGISTRY_ADDRESS
        value: 0x909fbFbFE9F7Bdb4d1a6e02F2E91d3f367555b07
      - key: TRADING_AGENT_ADDRESS
        value: 0x0D43DC16eFC1322Df3CE2B2852558993918A122B

      # Node Environment
      - key: NODE_ENV
        value: production

  # BaseTrader Service (Optional - can run as background worker)
  - type: worker
    name: zkml-base-trader
    env: node
    region: oregon
    plan: free
    buildCommand: cd news-service && npm install
    startCommand: cd news-service && node src/startBaseTrader.js
    envVars:
      # Same env vars as news-service
      - key: BASE_MAINNET_RPC_URL
        sync: false
      - key: ORACLE_PRIVATE_KEY
        sync: false
      - key: NEWS_ORACLE_CONTRACT_ADDRESS
        value: 0xe92c7aE9E894a8701583a43363676ff878d5b6ed
      - key: VERIFICATION_REGISTRY_ADDRESS
        value: 0x909fbFbFE9F7Bdb4d1a6e02F2E91d3f367555b07
      - key: TRADING_AGENT_ADDRESS
        value: 0x0D43DC16eFC1322Df3CE2B2852558993918A122B
      - key: UNISWAP_V3_ROUTER
        value: 0x2626664c2603336E57B271c5C0b26F421741e481
      - key: WETH_ADDRESS
        value: 0x4200000000000000000000000000000000000006
      - key: USDC_ADDRESS
        value: 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913
      - key: LOG_LEVEL
        value: info
      - key: NODE_ENV
        value: production
